### ISSUE TITLE
rust: leaked on `detectLeak`

### ISSUE THREAD

**Issue by kassane** [kassane/zig-gpa-ffi#1]
GPA [detectLeaks - src](https://ziglang.org/documentation/master/std/#std.heap.general_purpose_allocator.GeneralPurposeAllocator.detectLeaks) enabled

```bash
$ RUST_BACKTRACE=1 cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/zigGPA_global_allocator`
info(gpa): small alloc 56 bytes at u8@7b607ccea000
info(gpa): small alloc 40 bytes at u8@7b607ccea040
info(gpa): small alloc 1024 bytes at u8@7b607cce6000
Value at index 0: 2
Value at index 1: 4
Value at index 2: 6
Value at index 3: 8
Value at index 4: 10
Total sum of vector: 30
error(gpa): memory address 0x7b607ccea000 leaked: 
/home/kassane/zig-gpa-ffi/src/lib.zig:11:24: 0x5cf83d6f27fe in zigAlloc (zalloc)
    if (allocator.alloc(u8, size)) |buf| {
                       ^
rust/src/main.rs:10:18: 0x5cf83d6f0f32 in alloc (rust/src/main.rs/@/3fv17egqvah1imdgxzg6pr4he)
        unsafe { zigAlloc(layout.size()) }
                 ^
/home/kassane/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:194:17: 0x5cf83d6f1729 in lang_start<()> (rust/src/main.rs/@/6pksu6ut8s5l9uoduj54wsk71)
    let Ok(v) = lang_start_internal(
                ^
???:?:?: 0x7b607cac7ecb in ??? (libc.so.6)
???:?:?: 0x5cf83d6f0964 in ??? (???)

error(gpa): memory address 0x7b607ccea040 leaked: 
/home/kassane/zig-gpa-ffi/src/lib.zig:11:24: 0x5cf83d6f27fe in zigAlloc (zalloc)
    if (allocator.alloc(u8, size)) |buf| {
                       ^
rust/src/main.rs:10:18: 0x5cf83d6f0f32 in alloc (rust/src/main.rs/@/3fv17egqvah1imdgxzg6pr4he)
        unsafe { zigAlloc(layout.size()) }
                 ^
/home/kassane/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec.rs:412:15: 0x5cf83d6f21e5 in with_capacity_in<alloc::alloc::Global> (rust/src/main.rs/@/bltnw2g105dban99jghtkgloq)
        match Self::try_allocate_in(capacity, AllocInit::Uninitialized, alloc, elem_layout) {
              ^
/home/kassane/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:194:17: 0x5cf83d6f1729 in lang_start<()> (rust/src/main.rs/@/6pksu6ut8s5l9uoduj54wsk71)
    let Ok(v) = lang_start_internal(
                ^
???:?:?: 0x7b607cac7ecb in ??? (libc.so.6)
???:?:?: 0x5cf83d6f0964 in ??? (???)

error(gpa): memory address 0x7b607cce6000 leaked: 
/home/kassane/zig-gpa-ffi/src/lib.zig:11:24: 0x5cf83d6f27fe in zigAlloc (zalloc)
    if (allocator.alloc(u8, size)) |buf| {
                       ^
rust/src/main.rs:10:18: 0x5cf83d6f0f32 in alloc (rust/src/main.rs/@/3fv17egqvah1imdgxzg6pr4he)
        unsafe { zigAlloc(layout.size()) }
                 ^
std/src/sys/sync/once/futex.rs:177:21: 0x5cf83d6efc62 in call (std/src/lib.rs/@/std.c6eb78587944e35c-cgu.0)
std/src/sync/once.rs:217:9: 0x5cf83d6ef671 in initialize<std::sync::reentrant_lock::ReentrantLock<core::cell::RefCell<std::io::buffered::linewriter::LineWriter<std::io::stdio::StdoutRaw>>>, std::sync::once_lock::{impl#0}::get_or_init::{closure_env#0}<std::sync::reentrant_lock::ReentrantLock<core::cell::RefCell<std::io::buffered::linewriter::LineWriter<std::io::stdio::StdoutRaw>>>, std::io::stdio::stdout::{closure_env#0}>, !> (std/src/lib.rs/@/std.c6eb78587944e35c-cgu.0)
std/src/sync/once_lock.rs:390:9: 0x5cf83d7b9483 in _print (std/src/lib.rs/@/std.c6eb78587944e35c-cgu.0)
rust/src/main.rs:58:9: 0x5cf83d6f1ffe in {closure#0} (rust/src/main.rs/@/9vi37fp3ri5i0cngnipkvkl8j)
        println!("Value at index {}: {}", index, value);
        ^

info(gpa): small alloc 1 bytes at u8@7b607cccb000
info(gpa): small free 1 bytes at u8@7b607cccb000
thread 'main' panicked at rust/src/main.rs:66:9:
assertion failed: !leaked()
info(gpa): small alloc 512 bytes at u8@7b607cccb000
info(gpa): small resize 512 bytes at u8@7b607cccb000 to 25
panicked at core/src/panicking.rs:221:5:
unsafe precondition(s) violated: ptr::copy_nonoverlapping requires that both pointer arguments are aligned and non-null and the specified memory ranges do not overlap
thread panicked while processing panic. aborting.
```

**Comment by kassane** [comment]
**MacOS** - https://github.com/kassane/zig-gpa-ffi/actions/runs/12358802208/job/34490158042

```bash
Run cargo run
   Compiling zigGPA_global_allocator v0.1.0 (/Users/runner/work/zig-gpa-ffi/zig-gpa-ffi/rust)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 3.35s
     Running `/Users/runner/work/zig-gpa-ffi/zig-gpa-ffi/target/debug/zigGPA_global_allocator`
info(gpa): small alloc 64 bytes at u8@1043d8000
info(gpa): small alloc 40 bytes at u8@1043d8040
info(gpa): small alloc 1024 bytes at u8@1043e8000
info(gpa): small alloc 64 bytes at u8@1043d8080
Value at index 0: 2
Value at index 1: 4
Value at index 2: 6
Value at index 3: 8
Value at index 4: 10
Total sum of vector: 30
error(gpa): memory address 0x1043d8000 leaked: 
???:?:?: 0x104266ef7 in _zigAlloc (???)
rust/src/main.rs:10:18: 0x104265723 in alloc (rust/src/main.rs/@/1nd694od4rmpjwzi6njv5h1wh)
rust/src/main.rs:42:19: 0x104265bc7 in __rust_alloc (rust/src/main.rs/@/1nd694od4rmpjwzi6njv5h1wh)
???:?:?: 0x104314ac7 in __ZN3std6thread6Thread9new_inner17hf72df5a662df1b9dE (???)
???:?:?: 0x1043144e7 in __ZN3std2rt19lang_start_internal17h77891a2543177e4bE (???)
/rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/rt.rs:194:17: 0x104266b87 in lang_start<()> (rust/src/main.rs/@/cofuxgdjbgacedswpzrtmoyae)

error(gpa): memory address 0x1043d8040 leaked: 
???:?:?: 0x104266ef7 in _zigAlloc (???)
rust/src/main.rs:10:18: 0x104265723 in alloc (rust/src/main.rs/@/1nd694od4rmpjwzi6njv5h1wh)
rust/src/main.rs:42:19: 0x104265bc7 in __rust_alloc (rust/src/main.rs/@/1nd694od4rmpjwzi6njv5h1wh)
???:?:?: 0x104323127 in __ZN6memchr6memchr8fallback7memchr217h38dab6640d5cf3f6E (???)
/rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/alloc/src/raw_vec.rs:412:15: 0x1042666df in with_capacity_in<alloc::alloc::Global> (rust/src/main.rs/@/7qr2wh745ka9ag9cawg7oam26)
/rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/alloc/src/raw_vec.rs:189:20: 0x104265d0b in with_capacity<i32> (rust/src/main.rs/@/1u3qcmyikfihh3gvpkcc26yo1)

error(gpa): memory address 0x1043d8080 leaked: 
???:?:?: 0x104266ef7 in _zigAlloc (???)
rust/src/main.rs:10:18: 0x104265723 in alloc (rust/src/main.rs/@/1nd694od4rmpjwzi6njv5h1wh)
rust/src/main.rs:42:19: 0x104265bc7 in __rust_alloc (rust/src/main.rs/@/1nd694od4rmpjwzi6njv5h1wh)
???:?:?: 0x10431ad17 in __ZN3std3sys4sync5mutex7pthread14AllocatedMutex3new17h0685a95bbf6234c8E (???)
???:?:?: 0x1043352cf in __ZN3std3sys4sync8once_box16OnceBox$LT$T$GT$10initialize17hd3c004cd62d9b478E (???)
???:?:?: 0x104315c9f in __ZN3std2io5stdio6Stderr4lock17ha3df19dd37ed7051E (???)

error(gpa): memory address 0x1043e8000 leaked: 
???:?:?: 0x104266ef7 in _zigAlloc (???)
rust/src/main.rs:10:18: 0x104265723 in alloc (rust/src/main.rs/@/1nd694od4rmpjwzi6njv5h1wh)
rust/src/main.rs:42:19: 0x104265bc7 in __rust_alloc (rust/src/main.rs/@/1nd694od4rmpjwzi6njv5h1wh)
???:?:?: 0x104317ab3 in __ZN3std4sync4once4Once15call_once_force28_$u7b$$u7b$closure$u7d$$u7d$17hd99e267cf82614efE (???)
???:?:?: 0x10433550b in __ZN3std3sys4sync4once5queue4Once4call17h37550d946806f870E (???)
???:?:?: 0x1043350a3 in __ZN3std4sync9once_lock17OnceLock$LT$T$GT$10initialize17h6fce188f1418e336E (???)

info(gpa): small free 40 bytes at u8@1043d8040
info(gpa): small free 1024 bytes at u8@1043e8000
info(gpa): small free 64 bytes at u8@1043d8000
```

**Comment by kassane** [comment]
**Windows**: https://github.com/kassane/zig-gpa-ffi/actions/runs/12432450319/job/34711869895
```bash
   Compiling zigGPA_global_allocator v0.1.0 (D:\a\zig-gpa-ffi\zig-gpa-ffi\rust)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 22.43s
     Running `D:\a\zig-gpa-ffi\zig-gpa-ffi\target\debug\zigGPA_global_allocator.exe`
info(gpa): small alloc 64 bytes at u8@2cfed9a0000
info(gpa): small alloc 48 bytes at u8@2cfed9a0040
info(gpa): small alloc 1032 bytes at u8@2cfed9d0000
Value at index 0: 2
Value at index 1: 4
Value at index 2: 6
Value at index 3: 8
Value at index 4: 10
Total sum of vector: 30

thread 'main' has overflowed its stack
error: process didn't exit successfully: `D:\a\zig-gpa-ffi\zig-gpa-ffi\target\debug\zigGPA_global_allocator.exe` (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)
```
